### ISSUE TITLE
Not compatible with bootstrap 3.3.5

### ISSUE THREAD

**Issue by pivica** [markcarver/bootstrap-anchor#1]
Here is exception that is throwed

```
tooltip.js:120 Uncaught TypeError: Cannot set property 'hover' of undefined
```

When switch to tooltip.js from 3.3.4 version everything is OK.

**Comment by pedroposada** [comment]
thanks for this

**Comment by pehrlich** [comment]
+1

**Comment by markhalliwell** [comment]
PRs are welcome

**Comment by markhalliwell** [comment]
Latest release should have solved this: [change](https://github.com/unicorn-fail/bootstrap-anchor/compare/v0.0.1...v0.0.2#diff-bfaea224a524d8945fe2698de283a1c0R208)
