### ISSUE TITLE
Add bower support

### ISSUE THREAD

**Issue by OmgImAlexis** [markcarver/bootstrap-anchor#4]
If you added [bower](http://bower.io/) support it'd be easier for people that use bower to install and use this plugin.

**Comment by markhalliwell** [comment]
This is planned, once a full `1.0.0` version release has been made. This plugin is still in the initial development phase.

**Comment by OmgImAlexis** [comment]
@markcarver is there any reason not to add it now? I'm using it on a project and we're in the middle of moving to only bower with Grunt minifying everything so it'd help if we could add this as well instead of having to keep a separate file just for this library.

**Comment by markhalliwell** [comment]
PRs are welcome
