### ISSUE TITLE
load with requirejs

### ISSUE THREAD

**Issue by imoxx** [markcarver/bootstrap-anchor#6]
Hello,

how can I load this with requirejs. I tried to shim it like this:

```
'bootstrap-anchor': {
        deps: ['jquery', 'bootstrap'],
        exports: "$.fn.tooltip"
    }
```

but it does not work ;( 
I got this error: "Bootstrap Anchor requires the Bootstrap tooltip.js plugin, version 3.3.4 or greater."
It seems that bootstrap is not loaded.

**Comment by markhalliwell** [comment]
I don't use requirejs, PRs are welcome.
