### ISSUE TITLE
Remove Hash from URL + Back to top

### ISSUE THREAD

**Issue by teefars** [markcarver/bootstrap-anchor#7]
Since my website is multi language, it's hell on earth to change the ID's from each section (it's a Single Page Website), also, I really missed that option: I want to remove the hash from the URL after the scroll. My intention is to be as seamless as possible. I'm achieving this by adjusting manually some things, but it just seems wrong.
Also, would be great to have a "Back to Top" option/method.
Great plugin, love it

**Comment by markhalliwell** [comment]
Setting the `anchorHistory` [option](http://bootstrap-anchor.com/#options) to `false` will prevent it from changing the URL.

As far as the "Back to top" goes, just add an element at the top of the page, e.g. `<div id="top"></div>` and then you can add `<a href="#top">Back to top</a>` where ever you want.
